spring:
    application:
        name: user-auth-api
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
logging:
    level:
        #org.hibernate.SQL: DEBUG
        #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        #root: INFO
        it.tona.user_auth_api: INFO
    file: 
        path: logs/
    logback:
        rollingpolicy:
            max-history: 7

