spring:
  application:
    name: user-auth-api
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
logging:
  level:
    it.tona.user_auth_api: INFO
  file: 
    path: logs/
  logback:
    rollingpolicy:
      max-history: 7
