spring:
  application:
    name: user-auth-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    it.tona.user_auth_api]: INFO
  file: 
    path: logs/
  logback:
    rollingpolicy:
      max-history: 7

app.jwt.refreshExpirationSec: 3600

spring.mail.host=: live.smtp.mailtrap.io
spring.mail.port: 587
spring.mail.username: smtp@mailtrap.io
spring.mail.password: fefccff425dda9dbb7a77c8e063a8cec
spring.mail.protocol: smtp
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
