drop table if exists users cascade;


create table USER_AUTH_API.users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    full_name varchar(255) not null,
    password varchar(255) not null,
    role enum ('ADMIN','USER') not null,
    primary key (id)
);

create table USER_AUTH_API.user_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token varchar(255) not null unique,
    expiry_date timestamp not null,
    primary key (id),
    foreign key (user_id) references users(id) on delete cascade
);

create table USER_AUTH_API.password_reset_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token varchar(255) not null unique,
    expiry_date timestamp not null,
    primary key (id),
    foreign key (user_id) references users(id) on delete cascade
);

insert into users (email, full_name, password, role) values
    ('emelin@gmail.com', 'Emelin Tona', 'password', 'USER');
