drop table if exists users cascade;


create table users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    full_name varchar(255) not null,
    password varchar(255) not null,
    role enum ('ADMIN','USER') not null,
    primary key (id)
);

insert into users (email, full_name, password, role) values
    ('emelin@gmail.com', 'Emelin Tona', 'password', 'USER');